# ------------ navigation with ijkl ------------
[[mgr.prepend_keymap]]
on = [ "i" ]
run = "arrow -1"
desc = "Move cursor up"

[[mgr.prepend_keymap]]
on = [ "j" ]
run = "leave"
desc = "Go back to parent directory"

[[mgr.prepend_keymap]]
on = [ "k" ]
run = "arrow 1"
desc = "Move cursor down"

[[mgr.prepend_keymap]]
on = [ "l" ]
run = "enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "y"
run = [ "yank", "plugin clippy" ]
# ------------ ------------------- ------------

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "g" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"


[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
